{{- if .Values.jupyterhub.nfs.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-jupyterhub-nfs"
  labels:
    app: "{{ .Release.Name }}-jupyterhub-nfs"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-jupyterhub-nfs"
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google-samples/nfs-server:1.1
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - name: mypvc
            mountPath: /exports
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-jupyterhub-storage"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-jupyterhub-storage"
  labels:
    app: "{{ .Release.Name }}-jupyterhub-nfs"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  accessModes:
    - {{ .Values.jupyterhub.nfs.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.jupyterhub.nfs.persistence.size | quote }}
{{- if .Values.jupyterhub.nfs.persistence.storageClass }}
{{- if (eq "-" .Values.jupyterhub.nfs.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.jupyterhub.nfs.persistence.storageClass }}"
{{- end }}
{{- end }}
---
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-jupyterhub-nfs"
  labels:
    app: "{{ .Release.Name }}-jupyterhub-nfs"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: "{{ .Release.Name }}-jupyterhub-nfs"
{{- end }}
