#
#   Copyright 2017 EPAM Systems
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
version: "3"

services:
  base-python-image:
    build:
      context: base-python-image
    image: legion/base-python-image:latest
    networks:
      - legion_root
    restart: "no"

  jupyter:
    image: legion/base-python-image
    build:
      context: base-python-image
    networks:
      - legion_root
    labels:
      com.epam.legion.container_type: service
      com.epam.legion.container_description: Jupyter notebook server
    environment:
      - PYTHONPATH=/opt/project
      - PYDEVD_HOST
      - PYDEVD_PORT=5501
      - EXTERNAL_RESOURCE_USE_BY_DEFAULT=false
      - LOCAL_DEFAULT_RESOURCE_PREFIX=/legion
    entrypoint:
      - python3
      - -u
      - /opt/project/local-deployment/jupyter/jupyter.py
    working_dir: /opt/project/local-deployment/jupyter
    volumes:
      - ./workspace/legion:/legion
      - ./examples:/notebooks
      - ./:/opt/project

  grafana:
    build:
      context: local-deployment/grafana
    image: legion/grafana
    networks:
      - legion_root
    labels:
      com.epam.legion.container_type: service
      com.epam.legion.container_description: Grafana server
    environment:
      - PYTHONPATH=/opt/project
      - GF_SERVER_ROOT_URL=http://parallels/grafana
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_INSTALL_PLUGINS=
      - GF_GRAPHITE_DATASOURCE=http://graphite:80
    volumes:
      - ./workspace/legion:/legion
      - ./workspace/grafana:/var/lib/grafana
      - ./local-deployment/grafana/scripted_dashboards/model_builds.js:/usr/share/grafana/public/dashboards/model_builds.js
      - .:/opt/project

  graphite:
    image: hopsoft/graphite-statsd
    networks:
      - legion_root
    labels:
      com.epam.legion.container_type: service
      com.epam.legion.container_description: Graphite server
    volumes:
      - ./local-deployment/graphite/statsd/config.js:/opt/statsd/config_udp.js

  edge:
    depends_on:
      - consul
      - graphite
      - jupyter
    image: legion/edge
    build:
      context: local-deployment/edge
    networks:
      - legion_root
    labels:
      com.epam.legion.container_type: service
      com.epam.legion.container_description: Web server (load balancer)
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    ports:
      - 80:80
    volumes:
      - ./local-deployment/edge/static:/static
      - ./local-deployment/edge/nginx.conf.ctmpl:/nginx.conf.ctmpl

  consul:
    image: library/consul:latest
    networks:
      - legion_root
    labels:
      com.epam.legion.container_type: service
      com.epam.legion.container_description: Consul server (load balancer)
    ports:
      - 8500:8500

networks:
  legion_root:
    driver: bridge
