version: "3"

services:
  base-python-image:
    build:
      context: base-python-image
    image: drun/base-python-image:latest
    restart: "no"

  jupyter:
    image: drun/base-python-image
    environment:
      - PYTHONPATH=/opt/project
      - PYDEVD_HOST
      - PYDEVD_PORT=5501
    entrypoint:
      - python3
      - -u
      - /opt/project/jupyter/jupyter.py
    ports:
      - 8888:8888
    working_dir: /opt/project/jupyter
    volumes:
      - ./workspace/drun:/drun
      - ./examples:/notebooks
      - ./:/opt/project

  legion:
    depends_on:
      - consul
    image: drun/base-python-image
    environment:
      - PYTHONPATH=/opt/project
      - PYDEVD_HOST
      - PYDEVD_PORT=5502
    entrypoint:
      - python3
      - -u
      - /opt/project/drun/bin/legion
      - pyserve
    ports:
      - 5000:5000
    volumes:
      - ./workspace/drun:/drun
      - .:/opt/project

  grafana:
    image: drun/grafana
    environment:
      - PYTHONPATH=/opt/project
      - GF_SERVER_ROOT_URL=http://parallels/grafana
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
      - GF_GRAPHITE_DATASOURCE=http://graphite:80
    ports:
      - 3000:3000
    volumes:
      - ./workspace/drun:/drun
      - ./workspace/grafana:/var/lib/grafana
      - .:/opt/project
    logging:
      driver: none

  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - 81:80
      - 8126:8126
#    logging:
#      driver: none
    volumes:
      - ./graphite/config.js:/opt/statsd/config.js

  edge:
    depends_on:
      - consul
      - graphite
    image: drun/edge
    build:
      context: drun-edge
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    ports:
      - 80:80
    volumes:
      - ./drun-edge/nginx.conf.ctmpl:/nginx.conf.ctmpl
#    logging:
#      driver: none

  consul:
    image: library/consul:latest
    ports:
      - 8500:8500
    logging:
      driver: none
