#
#   Copyright 2017 EPAM Systems
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
version: "3"

services:
  base-python-image:
    build:
      context: base-python-image
    image: legion/base-python-image:latest
    networks:
      - legion_root
    restart: "no"

  jupyter:
    image: legion/base-python-image
    build:
      context: base-python-image
    networks:
      - legion_root
    labels:
      com.epam.legion.container_type: service
      com.epam.legion.container_description: Jupyter notebook server
    environment:
      - PYTHONPATH=/opt/project
      - PYDEVD_HOST
      - PYDEVD_PORT=5501
      - EXTERNAL_RESOURCE_USE_BY_DEFAULT=false
      - LOCAL_DEFAULT_RESOURCE_PREFIX=/legion
    entrypoint:
      - python3
      - -u
      - /opt/project/jupyter/jupyter.py
    ports:
      - 8888:8888
    working_dir: /opt/project/jupyter
    volumes:
      - ./workspace/legion:/legion
      - ./examples:/notebooks
      - ./:/opt/project

  legion:
    depends_on:
      - consul
    image: legion/base-python-image
    build:
      context: base-python-image
    networks:
      - legion_root
    labels:
      com.epam.legion.container_type: service
      com.epam.legion.container_description: Legion server (serves dummy model)
      com.epam.legion.container_required: 'false'
    environment:
      - PYTHONPATH=/opt/project
      - PYDEVD_HOST
      - PYDEVD_PORT=5502
    entrypoint:
      - python3
      - -u
      - /opt/project/legion/bin/legionctl
      - pyserve-dummy
    ports:
      - 5000:5000
    volumes:
      - ./workspace/legion:/legion
      - .:/opt/project

  grafana:
    build:
      context: grafana
    image: legion/grafana
    networks:
      - legion_root
    labels:
      com.epam.legion.container_type: service
      com.epam.legion.container_description: Grafana server
    environment:
      - PYTHONPATH=/opt/project
      - GF_SERVER_ROOT_URL=http://parallels/grafana
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_INSTALL_PLUGINS=
      - GF_GRAPHITE_DATASOURCE=http://graphite:80
    ports:
      - 3000:3000
    volumes:
      - ./workspace/legion:/legion
      - ./workspace/grafana:/var/lib/grafana
      - ./grafana/scripted_dashboards/model_builds.js:/usr/share/grafana/public/dashboards/model_builds.js
      - .:/opt/project

  jenkins:
    build:
      context: jenkins
    image: legion/jenkins
    networks:
      - legion_root
    labels:
      com.epam.legion.container_type: service
      com.epam.legion.container_description: Jenkins server
      com.epam.legion.container_required: 'false'
    environment:
      - DOCKER_HOST=${JENKINS_DOCKER_HOST}
      - LEGION_EXAMPLES_COMMIT=${LEGION_EXAMPLES_COMMIT}
      - DOCKER_CERT_PATH=/home/jenkins/.docker
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dpermissive-script-security.enabled=true -Dcom.epam.legion.jenkins.dashboard.url=/grafana/dashboard/script/model_builds.js?orgId=1&theme=light&model= -Dcom.epam.legion.jenkins.report.html.path=notebook.html"
      - legion_MODEL_SERVER_URL=http://edge:80
    ports:
      - 8081:8080
    volumes:
      - ${JENKINS_DOCKER_KEYS}:/home/jenkins/.docker
      - ./keys/git-deploy.key:/var/jenkins_home/.ssh/id_rsa
    logging:
      driver: none

  graphite:
    image: hopsoft/graphite-statsd
    networks:
      - legion_root
    labels:
      com.epam.legion.container_type: service
      com.epam.legion.container_description: Graphite server
    ports:
      - 81:80
      - 2003:2003
      - 8126:8126
      - 8125:8125/udp
#    logging:
#      driver: none
    volumes:
      - ./graphite/statsd/config.js:/opt/statsd/config_udp.js

  edge:
    depends_on:
      - consul
      - graphite
    image: legion/edge
    build:
      context: edge
    networks:
      - legion_root
    labels:
      com.epam.legion.container_type: service
      com.epam.legion.container_description: Web server (load balancer)
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    ports:
      - 80:80
    volumes:
      - ./edge/static:/static
      - ./edge/nginx.conf.ctmpl:/nginx.conf.ctmpl
#    logging:
#      driver: none

  consul:
    image: library/consul:latest
    networks:
      - legion_root
    labels:
      com.epam.legion.container_type: service
      com.epam.legion.container_description: Consul server (load balancer)
    ports:
      - 8500:8500
    logging:
      driver: none

networks:
  legion_root:
    driver: bridge
