apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  {{- include "odahuflow.ingress-aggregated-annotations" (dict "local" .Values.edge.ingress "root" .) | nindent 4 }}
  labels:
    {{- include "odahuflow.helm-labels" (dict "component" "service-catalog" "root" .) | nindent 4 }}
  name: "{{ .Release.Name }}-service-catalog"
spec:
  rules:
    - host: {{ include "odahuflow.ingress-domain-name" (dict "local" .Values.edge.ingress "root" . "tpl" "edge.%s") }}
      http:
        paths:
          - path: /swagger
            backend:
              serviceName: "{{ .Release.Name }}-service-catalog"
              servicePort: 5000
  {{- if (ternary $.Values.edge.ingress.tlsEnabled $.Values.ingress.tlsEnabled (hasKey $.Values.edge.ingress "tlsEnabled")) }}
  tls:
  - hosts:
    - {{ include "odahuflow.ingress-domain-name" (dict "local" .Values.edge.ingress "root" . "tpl" "edge.%s") | quote }}
    secretName: {{ include "odahuflow.ingress-tls-secret-name" (dict "local" .Values.edge.ingress "root" . ) | quote }}
  {{- end }}
