{{- if .Values.edi.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-edi"
  labels:
    {{- include "odahuflow.helm-labels" (dict "component" "edi" "root" .) | nindent 4 }}
spec:
  replicas: {{ .Values.edi.replicas }}
  selector:
    matchLabels:
      {{- include "odahuflow.helm-labels-for-search" (dict "component" "edi" "root" .) | nindent 6 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        {{- include "odahuflow.helm-labels" (dict "component" "edi" "root" .) | nindent 8 }}
    spec:
      {{- if .Values.rbac}}
      serviceAccountName: "{{ .Release.Name }}-edi"
      {{- end}}
      volumes:
        - name: config
          secret:
            secretName: "{{ .Release.Name }}-edi-config"
{{- if .Values.edi.volumes }}
{{ toYaml .Values.edi.volumes | indent 8 }}
{{- end }}
      containers:
      - name: edi
        image: "{{ include "odahuflow.image-name" (dict "root" . "service" .Values.edi "tpl" "%sodahuflow-edi:%s") }}"
        resources:
          {{- toYaml .Values.edi.resources | nindent 10 }}
        volumeMounts:
          - name: config
            mountPath: "/etc/odahuFlow"
            readOnly: true
{{- if .Values.edi.volumeMounts }}
{{ toYaml .Values.edi.volumeMounts | indent 10 }}
{{- end }}
        {{- if .Values.edi.env }}
        env:
          {{- range $key, $value := .Values.edi.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        {{- end }}
        command:
          - ./edi
        args:
          - --config
          - /etc/odahuFlow/config.yaml
        ports:
          - containerPort: 5000
            name: api
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 120
          timeoutSeconds: 8
          failureThreshold: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-edi"
  labels:
    {{- include "odahuflow.helm-labels" (dict "component" "edi" "root" .) | nindent 4 }}
spec:
  selector:
    {{- include "odahuflow.helm-labels-for-search" (dict "component" "edi" "root" .) | nindent 4 }}
  ports:
  - name: api
    targetPort: 5000
    port: {{ .Values.edi.port }}
    protocol: TCP
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-edi-config"
  labels:
    {{- include "odahuflow.helm-labels" (dict "component" "edi" "root" .) | nindent 4 }}
data:
  "config.yaml": |
    {{ toYaml .Values.config | b64enc }}
