---

- name: Configure kubectl using kops
  shell: "kops export kubecfg --name {{ cluster_name }} --state {{ state_store }}"

- include: create_enclave.yml
- include: install_legione.yml
- include: install_airflow.yml
