{{ if .Values.jenkins.enabled -}}
{{ if .Values.jenkins.rbac -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "deployments", "replicasets", "services", "pods/log", "pods/exec", "secrets"]
  verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
- apiGroups: ["extensions"]
  resources: ["deployments", "deployments/rollback", "deployments/scale", "replicasets", "statefulsets", "services"]
  verbs:  ["get", "watch", "list", "create", "delete", "deletecollection", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/rollback", "deployments/scale", "replicasets", "statefulsets", "services"]
  verbs:  ["get", "watch", "list", "create", "delete", "deletecollection", "patch", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: jenkins
roleRef:
  kind: Role
  name: jenkins
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
{{- end }}
{{- end }}

