version: 2.1
jobs:
  vulnerabilities:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo make install-vulnerabilities-checker
      - run: make check-vulnerabilities
  python_test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Setup miniconda
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda
      - run:
          name: Install deps
          command: |
            source "$HOME/miniconda/etc/profile.d/conda.sh"
            make install-all
            make install-python-tests
      - run:
          name: Code coverage
          command: |
            source "$HOME/miniconda/etc/profile.d/conda.sh"
            pip install codecov
            pip install pytest-cov
      - run:
          name: Test
          command: |
            source "$HOME/miniconda/etc/profile.d/conda.sh"
            make python-unittests
            bash <(curl -s https://codecov.io/bash) -cF python
  python_lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            make install-all
            make install-python-linter
      - run:
          name: Lint
          command: |
            make python-lint
  operator:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: sudo apt-get update -qq
      - run: sudo apt-get install wget make gcc pigz
      - run: wget -q https://github.com/golangci/golangci-lint/releases/download/v1.30.0/golangci-lint-1.30.0-linux-amd64.tar.gz -O /tmp/golangci-lint.tar.gz
      - run: sudo tar -zxvf /tmp/golangci-lint.tar.gz -C /usr/local/
      - run: sudo mv /usr/local/golangci-lint*/golangci-lint /usr/bin/golangci-lint
      - run: wget -q https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_linux_amd64.tar.gz -O /tmp/kubebuilder.tar.gz
      - run: sudo tar -zxvf /tmp/kubebuilder.tar.gz -C /usr/local/
      - run: sudo mv /usr/local/kubebuilder_* /usr/local/kubebuilder
      - run: wget -q https://github.com/swaggo/swag/releases/download/v1.6.5/swag_1.6.5_Linux_x86_64.tar.gz -O /tmp/swag.tar.gz
      - run: sudo tar -zxvf /tmp/swag.tar.gz -C /usr/local/
      - run: sudo mv /usr/local/swag /usr/bin/
      - run: wget -q https://github.com/gotestyourself/gotestsum/releases/download/v0.5.0/gotestsum_0.5.0_linux_amd64.tar.gz -O /tmp/gotestsum.tar.gz
      - run: sudo tar -zxvf /tmp/gotestsum.tar.gz -C /usr/local/
      - run: sudo mv /usr/local/gotestsum* /usr/bin/gotestsum
      - run: go get github.com/t-yuki/gocover-cobertura
      - run: cd packages/operator
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash) -cF go # (for codecov)
      - run: make lint
  feedback_aggregator:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: sudo apt-get update -qq
      - run: sudo apt-get install wget make gcc
      - run: wget -q https://github.com/golangci/golangci-lint/releases/download/v1.30.0/golangci-lint-1.30.0-linux-amd64.tar.gz -O /tmp/golangci-lint.tar.gz
      - run: sudo tar -zxvf /tmp/golangci-lint.tar.gz -C /usr/local/
      - run: sudo mv /usr/local/golangci-lint*/golangci-lint /usr/bin/golangci-lint
      - run: sudo wget -q https://github.com/golang/dep/releases/download/v0.5.1/dep-linux-amd64 -O /usr/local/bin/dep
      - run: sudo chmod +x /usr/local/bin/dep
      - run: wget -q https://github.com/gotestyourself/gotestsum/releases/download/v0.3.4/gotestsum_0.3.4_linux_amd64.tar.gz -O /tmp/gotestsum.tar.gz
      - run: sudo tar -zxvf /tmp/gotestsum.tar.gz -C /usr/local/
      - run: sudo mv /usr/local/gotestsum* /usr/bin/gotestsum
      - run: go get github.com/t-yuki/gocover-cobertura
      - run: cd packages/feedback
      - run: dep ensure -v -vendor-only
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash) -cF go # (for codecov)
      - run: make lint
  build:
    docker:
      - image: cimg/base:2021.01
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - setup_remote_docker
      - run: make docker-build-robot-tests
      - run: make docker-build-feedback-collector
      - run: make docker-build-feedback-rq-catcher
      - run: make docker-build-api
      - run: make docker-build-operator
      - run: make docker-build-model-trainer
      - run: make docker-build-model-packager
      - run: make docker-build-service-catalog

workflows:
  build_and_test:
    jobs:
      - vulnerabilities
      - python_test
      - python_lint
      - operator
      - feedback_aggregator
      - build:
          context:
            - hub.docker.com
          requires:
            - vulnerabilities
            - python_test
            - python_lint
            - operator
            - feedback_aggregator
