rootDomain: k8s-nightly.epm.kharlamov.biz
namespace: default
localDomain: "cluster.local"
addLocalDomain: true

IPs:
  external:
  - 172.31.12.63
  - 18.221.78.34

secrets:
  ldap:
    admin: "jonny"
  nexus:
    admin: "jonny"

  jupyterHub:
    cookieSecret: "67d0fa8039db03ecc683602e1aa66259b5af9c01acdd9d0b8817ff543372f3a0"
    secretToken: "1679182b276937843dbc0fe8a5a48b66a8dbf94f2e5bb67b27c8067253effeb7"

consul:
  service:
    labels:
      legion/system: yes
      legion/component: grafana  


edi:
  enabled: true
  replicas: 1
  image:
    repository: "legion/edi"
    tag: "latest"
    pullPolicy: "Always"

  rbac: true

  ingress:
    enabled: true
    annotations: {}
    domain:
      partial: edi
    tls:
      enabled: true
      autoSecretNameDeduction: true


edge:
  enabled: true
  replicas: 2
  image:
    repository: "legion/k8s-edge"
    tag: "latest"
    pullPolicy: "Always"

  # consul: "special-consul-address:8500"

  ingress:
    enabled: true
    annotations: {}
    domain:
      partial: edge
    tls:
      enabled: true
      autoSecretNameDeduction: true

jenkins:
  enabled: true
  image:
    repository: "legion/k8s-jenkins"
    tag: "latest"
    pullPolicy: "Always"

  rbac: true
  
  ingress:
    enabled: true
    annotations: {}
    domain:
      partial: jenkins
    tls:
      enabled: true
      autoSecretNameDeduction: true

  git_secret_name: false

graphite:
  enabled: true
  image:
    repository: "hopsoft/graphite-statsd"
    tag: "latest"
    pullPolicy: "Always"


grafana:
  enabled: true
  image:
    repository: "legion/k8s-grafana"
    tag: "latest"
    pullPolicy: "Always"

  # graphite: "aaaa"

  ingress:
    enabled: true
    annotations: {}
    domain:
      partial: grafana
    tls:
      enabled: true
      autoSecretNameDeduction: true

graphite:
  enabled: true

ldap:
  # LDAP Configuration
  server:
    # LDAP Server
    enabled: true
    organisation: "DRun"
    domain: "legion"

    ports:
      plain: 389
      ssl: 636

    image:
      repository: "osixia/openldap"
      tag: "1.1.10"
      pullPolicy: "Always"

    storage:
      accessMode: "ReadWriteOnce"
      size: "100m"


  gui:
    # LDAP GUI
    enabled: true
    replicas: 1
    # endpoint: "localhost"

    port: 80

    image:
      repository: "osixia/phpldapadmin"
      tag: "0.7.1"
      pullPolicy: "Always"

    ingress:
      enabled: true
      annotations: {}
      domain:
        partial: ldap
      tls:
        enabled: true
        autoSecretNameDeduction: true

jupyterhub:
  # Jupyter hub configuration
  enabled: false

  proxy:
    secretToken: "1679182b276937843dbc0fe8a5a48b66a8dbf94f2e5bb67b27c8067253effeb7"
    service:
      type: ClusterIP 
  
  nfs:
    enabled: true
    port: 80

    persistence:
      enabled: true
      storageClass: "hostpath"
      accessMode: ReadWriteOnce
      # existingClaim: ""
      size: 20Gi

    ingress:
      enabled: true
      annotations: {}
      domain:
        partial: nfs 
      tls:
        enabled: false

  ingress:
    enabled: true
    hosts:
    - jupyter.k8s-test.epm.kharlamov.biz

nexus:
  # Nexus repository configuration
  enabled: false
  replicas: 1

  image:
    repository: "cavemandaveman/nexus"
    tag: "3.6.0-02"

  resources: {}

  port: 8081
  hostport: 31110

  service:
    annotations: {}

  docker:
    enabled: true
    port: 5509
    hostport: 31111
    host: localhost

  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 30

  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 30
    failureThreshold: 6

  persistence:
    enabled: true
    storageClass: "hostpath"
    accessMode: ReadWriteOnce
    # existingClaim: ""
    size: 20Gi

  ## Create an Ingress for the Web UI
  ingress:
    enabled: true
    annotations: {}
    domain:
      partial: nexus
    tls:
      enabled: true
      autoSecretNameDeduction: true
      # secretName: nexus.k8s-nightly.epm.kharlamov.biz-tlsa

connections:
  docker:
    type: proxy
