kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: enclave
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          legion-component: core
    - namespaceSelector:
        matchLabels:
          k8s-component: ingress
    - namespaceSelector:
        matchLabels:
          enclave: {{ .Values.enclaveName }}
