---
- name: Get Ingress helm status
  shell: helm ls --all ing
  register: ingress_deployment_status

- set_fact:
    ingress_deployed: "{{ ingress_deployment_status.stdout_lines|length > 1 }}"

- name: Get public IP
  ipify_facts:

- name: Create Ingress configuration (values) file
  template:
    src: ingress-values.yaml.j2
    dest: ~/ingress-values.yaml
    mode: 0644
  vars:
    public_ip: "{{ ipify_public_ip }}"
    private_ip: "{{ inventory_hostname }}"
  when: not ingress_deployed

- name: Apply Ingress configuration
  shell: 'helm install stable/nginx-ingress --namespace kube-system --name ing -f ~/ingress-values.yaml'
  when: not ingress_deployed

- name: Wait for Ingress up
  shell: "kubectl get po --namespace kube-system | grep 'ingress'"
  register: ingress_list_status
  until: ingress_list_status.stdout.find(' Running') != -1
  retries: 5
  delay: 10
  ignore_errors: true
  when: not ingress_deployed

